GeekStreamProject/src/GeekStreamProject.App/Controllers/CategoriesController.cs
using GeekStream.Core.Abstractions;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeekStreamProject.App.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IUserService _userService;

        public CategoriesController(ICategoryService categoryService, IUserService userService)
        {
            _categoryService = categoryService;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Categories()
        {
            var categories = _categoryService.GetCategories();

            if (categories == null)
            {
                return NotFound();
            }
            ViewData["Title"] = "Категории";
            ViewBag.Users = _userService.GetUsers();
            return View(categories);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewData["Title"] = "Создание категории";
            ViewBag.Users = _userService.GetUsers();
            return View();
        }
        [HttpPost]
        public IActionResult Create(CategoryViewModel model)
        {
            _categoryService.Create(model);
            return RedirectToAction("Articles", "Articles");
        }

        
    }
        
}

GeekStreamProject/src/GeekStreamProject.App/Controllers/CommentController.cs
using GeekStream.Core.Abstractions;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace GeekStreamProject.App.Controllers
{
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;
        
        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        [HttpPost]
        public IActionResult Create(CreateCommentViewModel commentViewModel)
        {
            _commentService.Create(commentViewModel);

            return RedirectToAction("Article", "Articles", new { Id = commentViewModel.ArticleId});
        }

        [Route("ChangeHonor/{authorId}")]
        [HttpGet]
        public IActionResult ChangeHonor(int id, int delta, string authorId)
        {
            _commentService.ChangeHonor(id, delta);

            return RedirectToAction("UserInfo", "Users", new { userId = authorId });
        }

        [Route("ChangeHonor/{articleId:int}")]
        [HttpGet]
        public IActionResult ChangeHonor(int id, int delta, int articleId)
        {
            _commentService.ChangeHonor(id, delta);

            return RedirectToAction("Article", "Articles", new { Id = articleId });
        }
    }
}

GeekStreamProject/src/GeekStreamProject.App/Controllers/MessageController.cs
using GeekStream.Core.Abstractions;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Mvc;


namespace GeekStreamProject.App.Controllers
{
    public class MessageController : Controller
    {
        private readonly IMessageService _chatService;
        private readonly IUserService _userService;

        public MessageController(IMessageService chatService, IUserService userService)
        {
            _chatService = chatService;
            _userService = userService;
        }

        [HttpGet]
        public IActionResult CreateChat()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateChat(MessangerViewModel chat)
        {
            _chatService.CreateChat(chat);
            return RedirectToAction("Chats");
        }

        [HttpGet]
        public IActionResult Chats()
        {
            ViewBag.Users = _userService.GetUsers();
            ViewBag.Chats = _chatService.GetChats();
            return View("Chats");
        }

        [HttpGet]
        public IActionResult Chat(int id)
        {
            var chat = _chatService.GetChat(id);

            if (chat == null)
            {
                return NotFound();
            }

            ViewBag.Users = _userService.GetUsers();
            ViewBag.Chats = _chatService.GetChats();
            return View("Chats", chat);
        }

        [HttpGet]
        public IActionResult Dialog(string userName)
        {
            var dialog = _chatService.GetLatestDialogMessages(userName);
            ViewData["DialogReciever"] = userName;

            if(dialog == null)
            {
                return NotFound();
            }
            ViewBag.Users = _userService.GetUsers();
            return View("Dialog", dialog);
        }
    }
}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_ArticleCardPartial.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.ArticleViewModel>

@foreach (var item in Model)
{
    <div class="card text-dark bg-light mb-3">
        <div class="card-body">
            <div class="card-head">
                <div class="left row">
                    <strong>@item.Category.Name</strong>
                </div>
                <div class="right row">
                    <div class="col">
                        <img src="~/@item.Author.Avatar.Path" height="26" width="26" class="rounded-circle" />
                    </div>
                    <div class="col"><strong>@item.Author.UserName</strong></div>
                    <div class="col">
                        <div class="dropdown">
                            <img src="~/Assets/Imgs/Icons/Three dots.png" height="22" width="22" class="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item text-info" href=@Url.Action("Article", "Articles", new { Id = item.Id})>Читать полностью</a>
                                </li>
                                @if (User.IsInRole("Moder"))
                                {
                                    @if (item.ApprovedDate == null)
                                    {
                                        <li>
                                            <a class="dropdown-item text-secondary" href=@Url.Action("ApproveArticle", "Articles", new { Id = item.Id})>Одобрить</a>
                                        </li>
                                    }
                                    @if (item.ApprovedDate != null)
                                    {
                                        <li>
                                            <a class="dropdown-item text-secondary" href=@Url.Action("DisApproveArticle", "Articles", new { Id = item.Id})>Забраковать</a>
                                        </li>
                                    }
                                }
                                @if (item.Author.UserName == User.Identity.Name)
                                {
                                    @if (item.PublishedDate == null)
                                    {
                                        @if (item.ApprovedDate != null)
                                        {
                                            <li>
                                                <a class="dropdown-item text-success" href=@Url.Action("PublishArticle", "Articles", new { Id = item.Id})>Опубликовать</a>
                                            </li>
                                        }
                                        <li>
                                            <a class="dropdown-item text-dark" href=@Url.Action("Edit", "Articles", new { Id = item.Id})>Изменить</a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item text-danger" href=@Url.Action("Delete","Articles", new { Id=item.Id})>Удалить</a>
                                        </li>

                                    }
                                    @if (item.PublishedDate != null)
                                    {
                                        <li>
                                            <a class="dropdown-item text-dark" href=@Url.Action("DisPublishArticle", "Articles", new { Id = item.Id})>Вернуть в черновики</a>
                                        </li>
                                    }
                                    
                                }

                            </ul>
                        </div>
                    </div>
                </div>

            </div>

            <h3>
                    <a class="nav-link center card-title text-dark" article-title" href=@Url.Action("Article","Articles", new { Id = item.Id})>@item.Title</a>
            </h3>
            

            <div class="center">
                <div class="img-card-box zoomed-image">
                    <img src="~/@item.Image.Path" class="crop" />
                </div>
            </div>

            <p>
                <div class="card-text nav-text text-truncate">
                    @item.Content
                </div>
            </p>

            <div class="card-text nav-text">
                <img src="~/Assets/Imgs/Icons/Chat.png" height="22" width="22">
                @item.Comments.Count()
                <div class="right">
                    <div class="row row-cols-auto">
                        <div class="col">
                            <a asp-action="ChangeHonor" asp-controller="Articles" asp-route-id="@item.Id" asp-route-delta="+1">
                                <img src="~/Assets/Imgs/Icons/Caret up.png" height="22" width="22">
                            </a>
                        </div>
                        @if (item.Honor >= 0)
                        {
                            <div class="col">
                                <div class="text-success">
                                    @item.Honor
                                </div>
                            </div>
                        }
                        @if (item.Honor < 0)
                        {
                            <div class="col">
                                <div class="text-danger">
                                    @item.Honor
                                </div>
                            </div>
                        }
                        <div class="col">
                            <a asp-action="ChangeHonor" asp-controller="Articles" asp-route-id="@item.Id" asp-route-delta="-1">
                                <img src="~/Assets/Imgs/Icons/Caret down.png" height="22" width="22">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_ArticleListPartial.cshtml
@using GeekStream.Core.ViewModels
@model IEnumerable<GeekStream.Core.ViewModels.ArticleViewModel> 


<div class="accordion accordion-flush" id="articles">
        @foreach (var item in Model)
        {
            <div class="accordion-item">
                <h2 class="accordion-header" id="heading-@item.Id">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@item.Id" aria-expanded="false" aria-controls="collapse-@item.Id">
                        <div class="container">
                            <div class="row">
                                <div class="col-10"><strong>@item.Title</strong></div>
                                <div class="col-2"><strong>@item.Author.UserName</strong></div>
                            </div>
                        </div>     
                    </button>
                </h2>
                <div id="collapse-@item.Id" class="accordion-collapse collapse" aria-labelledby="heading-@item.Id" data-bs-parent="#articles">
                    <div class="accordion-body">
                        @item.Category.Name
                        <a class="btn btn-geekstream" href=@Url.Action("Article","Articles", new { Id=item.Id})>
                            Читать полностью
                        </a>
                        @if ((User.Identity.Name == item.Author.UserName) || User.IsInRole("Moder"))
                        {
                            <a class="btn btn-danger" href=@Url.Action("Delete","Articles", new { Id=item.Id})>Удалить</a>
                        }
                        <p>Оценка: @item.Honor</p>
                    </div>
                </div>
            </div>
        }
</div>

            

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CategoriesSideList.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.CategoryViewModel>

<div>
    @foreach(var category in Model)
    {
    <div class="card text-dark bg-light mb-3">
        <div class="card-body">
            <a class="nav-link text-dark" href=@Url.Action("ArticlesByCategory","Articles", new { Id = category.Id })>
                <img src="~/@category.Image.Path" width="24" height="24" />
                @Html.DisplayFor(modelItem => category.Name)
            </a>
        </div>
    </div>
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CategoryCardPartial.cshtml
@model GeekStream.Core.ViewModels.CategoryViewModel

<style>
    .img-category-card-box {
        width: 100%;
        height: 150px;
        overflow: hidden;
        position: relative;
    }
</style>

<div class="card text-dark bg-light mb-3">
    <div class="card-body text-dark">
        <div class="center">
            <div class="img-category-card-box zoomed-image">
                <img src="~/@Model.Image.BackGroundPath" class="crop" />
            </div>
        </div>
        <a class="nav-link text-dark left" href=@Url.Action("ArticlesByCategory","Articles", new { Id = Model.Id })>
            <strong>
                @Model.Name
            </strong>
        </a>

    </div>
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_ChatListPartial.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.MessageViewModel>
<input type="hidden" value="@User.Identity.Name" id="authenticatedUser"/>

<div  id="messagesList">
    @foreach (var message in Model)
    {
        @if (message.AuthorName == User.Identity.Name)
        {
        <div class="container">
            <div class=" d-flex justify-content-end">
                <div>
                    <div class="card bg-geekStream">
                        <div class="card-body">
                            <h5>@message.AuthorName</h5>
                            <p>@message.Content</p>
                        </div>
                    </div>
                    <small class="text-muted mb-1">@message.SendedTime</small>
                </div>
                
            </div>
        </div>
            
        }
        @if (message.AuthorName != User.Identity.Name || !User.Identity.IsAuthenticated)
        {
        <div class="container">
            <div class=" d-flex justify-content-start">
                <div>
                    <div class="card bg-geekStream">
                        <div class="card-body">
                            <h5>@message.AuthorName</h5>
                            <p>@message.Content</p>
                        </div>
                    </div>
                    <small class="text-muted mb-1">@message.SendedTime</small>
                </div>
                
            </div>
        </div>
            
        }
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CommentsListPartial.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.CommentViewModel>

@foreach (var comment in Model)
{
<div class="bg-light">
    <p class="card-header">
        @comment.AuthorName
    </p>
    <p class="card-body">
        @comment.Content
        <p>
            <a class="btn btn-success" asp-action="ChangeHonor" asp-controller="Comment" asp-route-id="@comment.Id" asp-route-delta="+1" asp-route-articleId="@comment.ArticleId"><img src="~/Assets/Imgs/Icons/Caret up.png" width="22" height="22"/></a>
            @comment.Honor
            <a class="btn btn-danger" asp-action="ChangeHonor" asp-controller="Comment" asp-route-id="@comment.Id" asp-route-delta="-1" asp-route-articleId="@comment.ArticleId"><img src="~/Assets/Imgs/Icons/Caret up.png" width="22" height="22" /></a>
        </p>
    </p>
</div>
}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CommentsListPartialUser.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.CommentViewModel>

@foreach (var comment in Model)
{
    <div class="bg-light">
        <p class="card-header">
            @comment.AuthorName
        </p>
        <p class="card-body">
            @comment.Content
        <p>
            <a class="btn btn-success" asp-action="ChangeHonor" asp-controller="Comment" asp-route-id="@comment.Id" asp-route-delta="+1" asp-route-authorId="@comment.AuthorId"><img src="~/Assets/Imgs/Icons/Caret up.png" width="22" height="22" /></a>
            @comment.Honor
            <a class="btn btn-danger" asp-action="ChangeHonor" asp-controller="Comment" asp-route-id="@comment.Id" asp-route-delta="-1" asp-route-authorId="@comment.AuthorId"><img src="~/Assets/Imgs/Icons/Caret up.png" width="22" height="22" /></a>
        </p>
        </p>
    </div>
}

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CreateCommentPartial.cshtml
@using GeekStream.Core.ViewModels
@model  GeekStream.Core.ViewModels.CreateCommentViewModel 

<h3>Новый комментарий</h3>
<hr />
<div class="form-group">
    <form asp-action="Create" asp-controller="Comment">
        <input type ="hidden" asp-for="@Model.ArticleId" />
        <textarea class="form-control" asp-for="@Model.Content" placeholder="Комментарий" required></textarea>
        <span asp-validation-for="@Model.Content" class="text-danger"></span>
        <div class="form-group">
            <input type="submit" value="Оставить комментарий" class="btn btn-primary" />
        </div>
    </form>
</div>
<hr />

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_CreateMessagePartial.cshtml
@model GeekStream.Core.ViewModels.MessageViewModel

@{
    var chatId = ViewData["ChatId"] as int?;
}
<div asp-validation-summary="ModelOnly"></div>

<form class="form-group mt-3" method="post">
    <input type="hidden" id="chatId" placeholder="айди чата" asp-for="@chatId" />
    <input type="hidden" id="userInput" placeholder="Имя пользователя" asp-for="@Model.AuthorName" />
    <textarea type="text" class="form-control" id="messageInput" placeholder="Ваше сообщение" asp-for="@Model.Content" required></textarea>
    <span asp-validation-for="@Model.Content" class="text-danger"></span>
    <button id="sendButton" class="btn btn-primary" type="button">Отправить</button>
</form>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeekStreamProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    
    <style>
        body {
            background: #E5E5E5;
        }
    </style>
</head>

<body>
    <header>
        @await Html.PartialAsync("_NavPartial")
    </header>

    <div class="container-s1 pt-3">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="center" align="center">
            Прав нет и не будет
        </div>
    </footer>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_NavPartial.cshtml
@using GeekStream.Core.Abstractions
@inject IUserService _userService;

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow justify-content-between">

    <ul class="nav justify-content-start">
        <li>
            <a href=@Url.Action("Articles","Articles")>
                <img src="~/Assets/Imgs/Logo.png">
            </a>
            
        </li>
        @if (User.Identity.IsAuthenticated)
        {
            @if (User.IsInRole("Moder"))
            {
                <li class="nav-item dropdown  nav-li-margin">
                    <a class="nav-text nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Статьи
                    </a>
                    <ul class="nav-text dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item nav-text " asp-controller="Articles" asp-action="NotApprovedArticles">Непроверенные</a></li>
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="NotPublishedArticles">Неопубликованные статьи</a></li>
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="Articles">Опубликованные</a></li>
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="NotPublishedUserArticles">Черновки</a></li>
                    </ul>
                </li>
            }
            else if (User.IsInRole("User"))
            {
                <li class="nav-item dropdown nav-li-margin">
                    <a class="nav-link dropdown-toggle nav-text" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Статьи
                    </a>
                    <ul class="nav-text dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="Articles">Статьи</a></li>
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="SubscriptionArticles">Отслеживаемое</a></li>
                        <li><a class="dropdown-item nav-text" asp-controller="Articles" asp-action="NotPublishedUserArticles">Черновки</a></li>
                    </ul>
                </li>
            }
        }
        else
        {
            <li class="nav-item nav-li-margin"><a class="nav-link nav-text" asp-controller="Articles" asp-action="Articles">Статьи</a></li>
        }
        <li class="nav-item  nav-li-margin">
            <a class="nav-link nav-text" asp-controller="Categories" asp-action="Categories">Категории</a>
        </li>
        <li class="nav-item  dropdown nav-li-margin">
            <a class="nav-link dropdown-toggle nav-text" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Пользователи
            </a>
            <ul class="nav-text dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item nav-text" asp-controller="Users" asp-action="Users">Пользователи</a></li>
                <li><a class="dropdown-item nav-text" asp-controller="Users" asp-action="Authors">Авторы</a></li>
            </ul>
        </li>
        <li>
            <a class="nav-link nav-text" asp-controller="Message" asp-action="Chats">Чат</a>
        </li>
        <li class="nav-item nav-li-margin">
            <a class="btn btn-geekstream" asp-controller="Articles" asp-action="Create">Создать статью</a>
        </li>
    <li class="nav-item nav-li-margin">
        @await Html.PartialAsync("_SearchingAreaSharedPartial")
    </li>
    </ul>
    <ul class="nav justify-content-end mr-5">
        @if (User.Identity.IsAuthenticated)
        {
            var user = _userService.GetUserById();
            
            <li class="nav-item">
                <div class="dropdown">
                    <a class="nav-link text-dark dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <strong class="mr-2">
                            @user.UserName
                        </strong>
                        <img src="~/@user.Avatar.Path" width="35" height="35" class="rounded-circle" />
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item text-secondary" asp-action="UserInfo" asp-controller="Users" asp-route-userId="@user.Id">Профиль</a>
                        </li>
                        <li>
                            <a class="dropdown-item text-danger" asp-action="UserSignOut" asp-controller="Users">Выйти</a>
                        </li>
                    </ul>
                </div>
                
            </li>           
        }
        else
        {
            <li class="nav-item">
                <a class="btn btn-common nav-text" asp-area="" asp-controller="Users" asp-action="Login">Вход</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-common nav-text" asp-area="" asp-controller="Users" asp-action="Registration">Регистрация</a>
            </li>
        }
    </ul>
</nav>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_SearchingAreaSharedPartial.cshtml
@{ 
    string line = "";
}
<form class="d-flex" asp-controller="Articles" asp-action="SearchArticle" method="get">
    <input class="form-control me-2 " asp-for="@line" type="search" placeholder="Поиск статей"  required />
</form>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_SubscriptionsSideList.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.UserViewModel>

<div>
    <div class="card text-dark bg-light mb-3">
        <div class="card-body text-dark">
            <a class="nav-link text-dark" href=@Url.Action("SubscriptionArticles","Articles")>
                Отслеживаемое
            </a>
        </div>
    </div>
    @foreach (var subscription in Model)
    {
        <div class="card text-dark bg-light mb-3">
            <div class="card-body text-dark">
                <a class="nav-link text-dark" href=@Url.Action("PublishedUserArticles","Articles", new { userId = subscription.Id })>
                    @Html.DisplayFor(modelItem => subscription.UserName)
                </a>
            </div>
        </div>
    }
</div>

GeekStreamProject/src/GeekStreamProject.App/Views/Shared/_UsersPartialMini.cshtml
@using System.Security.Claims;
@model IEnumerable<GeekStream.Core.ViewModels.UserViewModel>

<div>
    @foreach (var item in Model)
    {
        <div class="card text-dark bg-light mb-3">
            <div class="card-header">
                @if (item.Confirmed)
                {
                    <img src="~/@item.Avatar.Path" class="rounded-circle border border-success" width="40" height="40" />
                }
                @if (!item.Confirmed)
                {
                    <img src="~/@item.Avatar.Path" class="rounded-circle border border-danger" width="40" height="40" />
                }
                <a class="btn text-dark" href=@Url.Action("UserInfo","Users", new { userId = item.Id})>@item.UserName</a>
                @if (User.Identity.IsAuthenticated)
                {
                    @if (!(User.FindFirst(ClaimTypes.NameIdentifier).Value == item.Id))
                    {
                        <a class="btn btn-common right" href=@Url.Action("Dialog", "Message", new { UserName = item.UserName })><img src="~/Assets/Imgs/Icons/Chat.png" height="20" width="20"/></a>
                    }
                }
            </div>
        </div>
    }
</div>